// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1, arg2) {
  return window['go']['backend']['MailgridService']['CancelJob'](arg1, arg2);
}

export function ListJobs(arg1) {
  return window['go']['backend']['MailgridService']['ListJobs'](arg1);
}

export function Preview(arg1) {
  return window['go']['backend']['MailgridService']['Preview'](arg1);
}

export function Run(arg1) {
  return window['go']['backend']['MailgridService']['Run'](arg1);
}

export function RunScheduler(arg1) {
  return window['go']['backend']['MailgridService']['RunScheduler'](arg1);
}

export function ScheduleJob(arg1) {
  return window['go']['backend']['MailgridService']['ScheduleJob'](arg1);
}

export function SendTestEmail(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['MailgridService']['SendTestEmail'](arg1, arg2, arg3, arg4);
}
