// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function CancelJob(arg1:string,arg2:string):Promise<void>;

export function ListJobs(arg1:string):Promise<Array<Record<string, any>>>;

export function Preview(arg1:backend.UIArgs):Promise<void>;

export function Run(arg1:backend.UIArgs):Promise<void>;

export function RunScheduler(arg1:string):Promise<void>;

export function ScheduleJob(arg1:backend.UIArgs):Promise<void>;

export function SendTestEmail(arg1:context.Context,arg2:string,arg3:string,arg4:string):Promise<void>;
