// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMailgrid(arg1) {
  return window['go']['main']['App']['CallMailgrid'](arg1);
}

export function CancelScheduledJob(arg1, arg2) {
  return window['go']['main']['App']['CancelScheduledJob'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListScheduledJobs(arg1) {
  return window['go']['main']['App']['ListScheduledJobs'](arg1);
}

export function LoadSMTPConfig(arg1) {
  return window['go']['main']['App']['LoadSMTPConfig'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['main']['App']['OpenFile'](arg1, arg2);
}

export function OpenSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenSaveFile'](arg1, arg2, arg3);
}

export function PreviewMailgrid(arg1) {
  return window['go']['main']['App']['PreviewMailgrid'](arg1);
}

export function SaveSMTPConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveSMTPConfig'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2);
}

export function ScheduleMailgrid(arg1) {
  return window['go']['main']['App']['ScheduleMailgrid'](arg1);
}

export function StartScheduler(arg1) {
  return window['go']['main']['App']['StartScheduler'](arg1);
}
