// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CallMailgrid(arg1:backend.UIArgs):Promise<Record<string, any>>;

export function CancelScheduledJob(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function ListScheduledJobs(arg1:string):Promise<Record<string, any>>;

export function LoadSMTPConfig(arg1:string):Promise<Record<string, any>>;

export function OpenFile(arg1:string,arg2:Array<string>):Promise<string>;

export function OpenSaveFile(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function PreviewMailgrid(arg1:backend.UIArgs):Promise<Record<string, any>>;

export function SaveSMTPConfig(arg1:Record<string, any>,arg2:string):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function ScheduleMailgrid(arg1:backend.UIArgs):Promise<Record<string, any>>;

export function StartScheduler(arg1:string):Promise<Record<string, any>>;
